name: TerraEC2 CI/CD

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: "Configure AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.0.0
                  
            - name: Check terraform version
              run: terraform --version

            - name: Install Terraform
              run: terraform init

            - name: Terraform Format
              run: terraform fmt -check

            - name: Terraform Plan
              run: terraform plan -input=false

