name: TerraEC2 CI/CD

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup AWS
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.0.0
                  
            - name: Check terraform version
              uses: terraform --version

            - name: Install Terraform
              run: terraform init
              working-directory: ./terraform
            - name: Terraform Format
              run: terraform fmt -check
              working-directory: ./terraform
            - name: Terraform Validate
              run: terraform validate
              working-directory: ./terraform
            - name: Terraform Plan
              run: terraform plan
              working-directory: ./terraform
