name: TerraEC2 CI/CD

on:
    push:
    pull_request:

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.0.0
            
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
            
            - name: Install AWS CLI
              run: |
                  python -m pip install --upgrade pip
                  pip install awscli
                  aws --version
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set region ${{ secrets.AWS_REGION }}
                  aws --version
                  pwd
                  ls -lrth
                  terraform --version
    test:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Install Terraform
              run: terraform init
              working-directory: ./terraform
            - name: Terraform Format
              run: terraform fmt -check
              working-directory: ./terraform
            - name: Terraform Validate
              run: terraform validate
              working-directory: ./terraform
            - name: Terraform Plan
              run: terraform plan
              working-directory: ./terraform
